bwa2018djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from normaluser import views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('registration/', views.user_registration, name='registration'),
    path('registration/email_authenticate_registration/<slug:email_validation_code>',
         views.email_authenticate_registration, name='email_authenticate_registration'),
    path('password_reset/', views.user_password_reset, name='password_reset'),
    path('password_recover/<slug:username>', views.password_recover, name='password_recover'),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('normaluser.urls', 'normaluser'), namespace='normaluser')),
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
    path('discussion/', include(('discussion.urls', 'discussion'), namespace='discussion')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),  # for social login authentication
]

urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bwa2018djangoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('comment_add/', views.comment_add, name='comment_add'),
    path('more_status_after_mouse_scroll/<slug:last_item_id>', views.more_status_after_mouse_scroll,
         name='more_status_after_mouse_scroll'),
    path('status_details/<slug:post_id>', views.status_details,
         name='status'),
    path('edit_post/<slug:post_id>', views.edit_post, name='edit_post'),
    path('delete_post/<slug:post_id>', views.delete_post, name='delete_post'),
    path('get_comment/<slug:comment_id>', views.get_comment, name='get_comment'),
    path('delete_comment/<slug:comment_id>/<slug:post_id>', views.delete_comment, name='delete_comment'),
    path('cancel_comment_edit/<slug:comment_id>/<slug:post_id>', views.cancel_comment_edit, name='cancel_comment_edit'),
    path('comment_update', views.comment_update, name="comment_update")
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

normaluser/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from bwa2018djangoproject import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.profile, name='profile'),
    path(r'edit/', views.edit_profile, name='edit_profile'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('upload_profile_image', views.upload_profile_image, name='upload_profile_image'),
    path('delete_account', views.delete_account, name='delete_account'),
    # path('other/<slug:username1>.+', views.user_profile, name='other'),
    re_path(r'^other/(?P<username1>.*)/$', views.user_profile, name='other'),
    re_path(r'^user_search/$', views.user_search, name='user_search'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

normaluser/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models

GENDER_CHOICES = (
    ('m', 'Male'),
    ('f', 'Female')
)


class NormalUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='m')
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=16)
    birth_date = models.DateField(null=True, blank=True)
    profile_photo = models.ImageField(upload_to='profile_image', blank=True)
    email_validation_code = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.user.username

normaluser/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
# from django.db import connection
from django.contrib.sites.shortcuts import get_current_site
from django.core import mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib import messages

from _datetime import datetime
from . import forms
from . import models
from home.models import Post, Comment
from friends.models import Friend
from notification.models import Notification
from discussion.models import DiscussionHead, Discussion, DiscussionRecipient, DiscussionUserGroup
from django.contrib.auth.models import User
from django.db.models import Q
import hashlib


# login templates, authenticate and login a user
def user_login(request):
    if request.method == 'POST':
        login_form = forms.LoginForm(request.POST)
        if login_form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user_object = models.User.objects.get(email=email)
            user = authenticate(username=user_object.username, password=password)
            login(request, user)
            # messages.success(request, "Your account has been activated successfully. Now you can login.")
            return redirect('/')

    else:
        login_form = forms.LoginForm()

    return render(request, 'login/login.html', {'login_form': login_form})


def computeMD5Hash(string):
    m = hashlib.md5()
    m.update(string.encode('utf-8'))
    return m.hexdigest()


def user_registration(request):
    now = datetime.now()

    user_form = forms.RegistrationForm()
    profile_form = forms.UserProfileInfoForm({'gender': 'm'})
    if request.method == 'POST':
        user_form = forms.RegistrationForm(request.POST)
        profile_form = forms.UserProfileInfoForm(request.POST)
        if user_form.is_valid():

            user_object = models.User()
            user_object.first_name = user_form.data['first_name']
            user_object.last_name = user_form.data['last_name']
            user_object.username = user_form.data['username']
            user_object.email = user_form.data['email']
            user_object.password = make_password(user_form.data['password'])
            user_object.is_active = False
            user_object.save()

            profile_object = models.NormalUser()

            year = 1970
            if request.POST['year'] != '':
                year = request.POST['year']

            month = 12
            if request.POST['month'] != '':
                month = request.POST['month']

            day = 12
            if request.POST['day'] != '':
                day = request.POST['day']

            profile_object.birth_date = datetime.strptime(str(year)+'-'+str(month)+'-'+str(day), "%Y-%m-%d").date()
            profile_object.address = profile_form.data['address']
            profile_object.phone_number = profile_form.data['phone_number']
            profile_object.gender = profile_form.data['gender']
            profile_object.user_id = user_object.id
            profile_object.email_validation_code = computeMD5Hash(user_object.username)

            profile_object.save()
            current_site = get_current_site(request)

            html_content = render_to_string('registration/email_authentication.html',
                                            {'email_authentication_code': profile_object.email_validation_code,
                                             'first_name': user_object.first_name,
                                             'last_name': user_object.last_name, 'domain': current_site.domain})
            text_content = strip_tags(html_content)

            connection = mail.get_connection()
            connection.open()
            email1 = mail.EmailMessage(
                'Confirm your account on Social site',
                text_content,
                'sazzad.rupak17@gmail.com',
                [user_object.email],
                connection=connection
            )
            email1.send()
            connection.close()

            return render(request, 'registration/email_sent_message.html', {
                'email_authentication_code': profile_object.email_validation_code, 'first_name': user_object.first_name,
                'last_name': user_object.last_name})
        else:
            return render(request, 'registration/registration.html', {'user_form': user_form, 'profile_form': profile_form})
    else:
        return render(request, 'registration/registration.html', {'user_form': user_form, 'profile_form': profile_form,
                                                                  'days': range(1, 32, 1), 'months': range(1, 13, 1),
                                                                  'years': range(now.year, 1970, -1)})


# Check if an email id is unique or not
def check_uniqe_email_id(request):
    email = request.GET.get('email_id')

    match = models.User.objects.filter(email=email).exists()
    # print(connection.queries)
    return JsonResponse({'is_taken': match}, safe=False)


# activate an account by clicking the activation link
def email_authenticate_registration(request, email_validation_code):
    p = models.NormalUser.objects.get(email_validation_code=email_validation_code)
    user_object = models.User.objects.get(id=p.user.id)
    user_object.is_active = True
    user_object.save()

    p.email_validation_code = ''
    p.save()
    messages.success(request, "Your account has been activated successfully. Now you can login.")
    return HttpResponseRedirect('/')


def user_logout(request):
    logout(request)
    return redirect('login/')


def user_password_reset(request):
    reset_form = forms.UserPasswordResetForm()
    if request.method == 'POST':
        reset_form = forms.UserPasswordResetForm(request.POST)
        if reset_form.is_valid():
            email = reset_form.data['email']
            user_object = User.objects.get(email=email)
            encrypted_username = computeMD5Hash(user_object.username)

            normal_user_object = models.NormalUser.objects.get(user_id=user_object.id)
            normal_user_object.email_validation_code = encrypted_username
            normal_user_object.save()
            current_site = get_current_site(request)
            html_content = render_to_string('registration/password_reset_email.html',
                                            {
                                                'username': encrypted_username,
                                                'first_name': user_object.first_name,
                                                'last_name': user_object.last_name, 'domain': current_site.domain})
            text_content = strip_tags(html_content)

            connection = mail.get_connection()
            connection.open()
            email1 = mail.EmailMessage(
                'Confirm your account on Social site',
                text_content,
                'sazzad.rupak17@gmail.com',
                [email],
                connection=connection
            )
            email1.send()
            connection.close()
            return render(request, 'registration/password_reset_email_sent.html', {'first_name': user_object.first_name,
                                                                               'last_name': user_object.last_name})
        else:
            return render(request, 'registration/password_reset_form.html', {'reset_form': reset_form})
    else:
        return render(request, 'registration/password_reset_form.html', {'reset_form': reset_form})


def password_recover(request, username):
    if models.NormalUser.objects.filter(email_validation_code=username).count() > 0:
        password_change_form = forms.AccountPasswordChangeForm()
        if request.method == 'POST':
            password_change_form = forms.AccountPasswordChangeForm(request.POST)
            if password_change_form.is_valid():
                new_password = password_change_form.data['password']
                normal_user_object = models.NormalUser.objects.get(email_validation_code=username)
                user_object = models.User.objects.get(id=normal_user_object.user_id)
                user_object.password = make_password(new_password)
                user_object.save()

                normal_user_object.email_validation_code = ''
                normal_user_object.save()

                messages.success(request, "Your password has been updated successfully. Login with new password.")
                return HttpResponseRedirect('/')
        return render(request, 'registration/password_recover_form.html', {'password_change_form': password_change_form})
    else:
        messages.error(request, "No password reset request has been found.")
        return HttpResponseRedirect('/')


@login_required(login_url='login')
def profile(request):
    if request.user.is_authenticated:
        now = datetime.now()
        try:
            profile_data = models.NormalUser.objects.get(user_id=request.user.id)
            page_name = 'Profile'
            user_form = forms.ProfileUpdateForm(instance=models.User.objects.get(id=request.user.id))
            profile_form = forms.UserProfileInfoForm(instance=profile_data)
            image_form = forms.ProfileImageUpload()
            day = profile_data.birth_date.day
            month = profile_data.birth_date.month
            year = profile_data.birth_date.year
            posts_count = Post.objects.filter(user_id=request.user.id).count()
            friends = Friend.objects.filter((Q(user_one_id=request.user.id) | Q(user_two_id=request.user.id)) &

normaluser/templates/normaluser/profile-edit.html
{% extends "layout.html" %}
{% block title %} Your Profile {% endblock %}
{% load static from staticfiles %}
{% block content %}
    <div id="home-page">
        <div class="container">
            <div class="row">
                <!-- profile info section starts here-->
                <div class="col-sm-6" style="margin: 0 auto; float: none"><!--left col-->
                    <div class="align-center">
                        {% if profile_data.profile_photo == '' %}
                            <img src="{% static "normaluser/images/avatar_2x.png" %}" class="user-profile-img img-fluid img-thumbnail" alt="avatar">
                        {% else %}
                            <img src="{% static profile_data.profile_photo.url %}"  class="user-profile-img img-fluid img-thumbnail" alt="avatar">
                        {% endif %}
                        <form enctype="multipart/form-data" method="post" action="{% url 'normaluser:upload_profile_image' %}">
                            {% csrf_token %}
                            <input type="hidden" name="next_url" value="{{ request.path }}">
                            {% for field in image_form %}
                                {% if field.errors %}
                                    <div class="form-group has-error has-feedback">
                                        <label class="control-label">{{ field.label }}</label>
                                        <div class="controls">{{ field }}
                                            <span class="help-block">
                                                {% for error in  field.errors %}{{ error }}{% endfor %}
                                            </span>
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="input-group col-xs-8 align-center" style="margin-bottom: 10px; margin-top: 10px;">
                                            {{ field }}
                                            {% if field.help_text %}
                                                <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                            {% endif %}
                                            <span class="input-group-btn">
                                               <button type="submit" class="form-control btn btn-primary">Upload photo</button>
                                            </span>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </form>
                    </div>
                    </hr>
                    <div class="profile-info" style="padding: 10px;">
                            <form class="form" action="{% url 'normaluser:update_profile' %}" method="post" id="profileUpdateForm">
                                {% csrf_token %}
                                {% for field in user_form %}
                                    {% if field.errors %}
                                        <div class="form-group has-error has-feedback">
                                            <label class="control-label">{{ field.label }}</label>
                                            <div class="controls">{{ field }}
                                                <span class="help-block">
                                                    {% for error in  field.errors %}{{ error }}{% endfor %}
                                                </span>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="form-group">
                                            <label class="control-label">{{ field.label }} *</label>
                                            <div class="controls">{{ field }}
                                                {% if field.help_text %}
                                                    <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}

                                {% for field in user_form.non_field_errors %}
                                    <div class="form-group has-error has-feedback">
                                        <div class="controls">
                                            <span class="help-block">
                                                {{ field }}
                                            </span>
                                        </div>
                                    </div>
                                {% endfor %}

                                {% for field in profile_form %}
                                    {% if field.errors %}
                                        <div class="form-group has-error has-feedback">
                                            <label class="control-label">{{ field.label }}</label>
                                            <div class="controls">{{ field }}
                                                <span class="help-block">
                                                    {% for error in  field.errors %}{{ error }}{% endfor %}
                                                </span>
                                            </div>
                                        </div>
                                    {% else %}
                                        {% if field.label is 'Gender' %}
                                            <label class="radio-inline"><input type="radio" name="optradio" checked>Option 1</label>
                                        {% else %}
                                            <div class="form-group">
                                                <label class="control-label">{{ field.label }}</label>
                                                <div class="controls">{{ field }}
                                                    {% if field.help_text %}
                                                        <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                                <div class="form-group">
                                    <label class="control-label">Date of birth</label>
                                    <div class="input-group">
                                        <span class="input-group-btn">
                                            <select class="form-control" name="day" id="day">
                                                <option value="">Day</option>
                                                {% for day in days %}
                                                    {% if birth_day == day %}
                                                        <option selected="selected" value="{{ day }}">{{ day }}</option>
                                                    {% else %}
                                                        <option value="{{ day }}">{{ day }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                        </span>
                                        <span class="input-group-btn">
                                            <select class="form-control" name="month" id="month">
                                                <option value="">Month</option>
                                                {% for month in months %}
                                                    {% if birth_month == month %}
                                                        <option selected="selected" value="{{ month }}">{{ month }}</option>
                                                    {% else %}
                                                        <option value="{{ month }}">{{ month }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                        </span>
                                        <span class="input-group-btn">
                                            <select class="form-control" name="year" id="year">
                                                <option value="">Year</option>
                                                {% for year in years %}
                                                    {% if birth_year == year %}
                                                        <option selected="selected" value="{{ year }}">{{ year }}</option>
                                                    {% else %}
                                                        <option value="{{ year }}">{{ year }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </form>

                    </div>
                </div>
                <!-- profile info section ends here-->



            </div>

        </div>
    </div>
{% endblock %}

normaluser/templates/normaluser/user_profile_lucas.html
{% extends "layout.html" %}
{% block title %} {{ profile_data.username }} {% endblock %}
{% load static from staticfiles %}
{% block static %}
	<link rel="stylesheet" type="text/css" href="{% static 'normaluser/css/layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/home.css' %}">
{% endblock %}
{% block content %}
    <div id="home-page">
        <div class="container">
            <div class="row">
                <div class="col-sm-12"><h1>{{ profile_data.username }}</h1></div>
            </div>
            <div class="row">
                <div class="col-sm-3"><!--left col-->
                    <div class="text-center">
                        {% if profile_data.profile_photo == '' %}
                            <img src="{% static "normaluser/images/avatar_2x.png" %}" class="avatar img-circle img-thumbnail" alt="avatar">
                        {% else %}
                            <img src="{% static profile_data.profile_photo.url %}" width="180" height="180" alt="avatar">
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-9">
                    <div class="tab-content">
                        <div class="tab-pane active" id="view">
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Username:</td>
                                        <td>{{ profile_data.username }}</td>
                                    </tr>
                                    <tr>
                                        <td>First name</td>
                                        <td>{{ profile_data.first_name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Last name</td>
                                        <td>{{ profile_data.last_name }}</td>
                                    </tr>

                                    {%  if is_friend > 0 %}
                                    <tr>
                                        <td>Gender</td>
                                        <td>
                                            {% if profile_data.gender == 'm' %}
                                            Male
                                            {% else %}
                                            Female
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Home Address</td>
                                        <td>{{ profile_data.address }}</td>
                                    </tr>

                                    <tr>
                                        <td>Email</td>
                                        <td><a href="{{ profile_data.email }}">{{ profile_data.email }}</a></td>
                                    </tr>

                                    <tr>
                                        <td>Phone Number</td>
                                        <td>{{ profile_data.phone_number }}</td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                            <hr>
                        </div><!--/tab-pane-->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}