bwa2018djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from normaluser import views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('registration/', views.user_registration, name='registration'),
    path('registration/email_authenticate_registration/<slug:email_validation_code>',
         views.email_authenticate_registration, name='email_authenticate_registration'),
    path('password_reset/', views.user_password_reset, name='password_reset'),
    path('password_recover/<slug:username>', views.password_recover, name='password_recover'),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('normaluser.urls', 'normaluser'), namespace='normaluser')),
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
    path('discussion/', include(('discussion.urls', 'discussion'), namespace='discussion')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),  # for social login authentication
]

urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bwa2018djangoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('comment_add/', views.comment_add, name='comment_add'),
    path('more_status_after_mouse_scroll/<slug:last_item_id>', views.more_status_after_mouse_scroll,
         name='more_status_after_mouse_scroll'),
    path('status_details/<slug:post_id>', views.status_details,
         name='status'),
    path('edit_post/<slug:post_id>', views.edit_post, name='edit_post'),
    path('delete_post/<slug:post_id>', views.delete_post, name='delete_post'),
    path('get_comment/<slug:comment_id>', views.get_comment, name='get_comment'),
    path('delete_comment/<slug:comment_id>/<slug:post_id>', views.delete_comment, name='delete_comment'),
    path('cancel_comment_edit/<slug:comment_id>/<slug:post_id>', views.cancel_comment_edit, name='cancel_comment_edit'),
    path('comment_update', views.comment_update, name="comment_update")
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

normaluser/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from bwa2018djangoproject import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.profile, name='profile'),
    path(r'edit/', views.edit_profile, name='edit_profile'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('upload_profile_image', views.upload_profile_image, name='upload_profile_image'),
    path('delete_account', views.delete_account, name='delete_account'),
    # path('other/<slug:username1>.+', views.user_profile, name='other'),
    re_path(r'^other/(?P<username1>.*)/$', views.user_profile, name='other'),
    re_path(r'^user_search/$', views.user_search, name='user_search'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    post_text = models.TextField(max_length=200)
    post_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at', ]

    def __str__(self):
        return self.post_text


class Comment(models.Model):
    post = models.ForeignKey('home.Post', on_delete=models.CASCADE, related_name='comments')
    comment_text = models.TextField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at', ]

    def __str__(self):
        return self.comment_text

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from .models import Post, Comment


class StatusTextForm(forms.Form):
    status_text = forms.CharField(required=True, widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write something to share with your friends',
            'rows': 3,
            'cols': 12,
            'max-length': '200',
        }
    ))

    def clean(self):
        data = self.cleaned_data
        if data.get('status_text') == '':
            raise forms.ValidationError('Please write something before post.')
        data['status_text'] = data.get('status_text')

        return data

    class Meta:
        model = Post
        fields = ['status_text']


def must_be_empty(value):
    if value:
        raise forms.ValidationError('is not empty')


class CommentTextForm(forms.Form):
    comment_text = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Add comment here',
            'max-length': '100',
        }
    ))
    honeypot = forms.CharField(required=False, widget=forms.HiddenInput, label="Leave empty", validators=[must_be_empty])

    def clean(self):
        data = self.cleaned_data
        if data.get('comment_text') == '':
            raise forms.ValidationError('Please write something before post.')
        data['comment_text'] = data.get('comment_text')

        return data

    class Meta:
        model = Comment
        fields = ['comment_text']

home/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from . import forms
from . import models

from django.db.models import Q
from django.contrib.auth.models import User
from friends.models import Friend

from notification.models import Notification
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
# Create your views here.


@login_required(login_url='login')
def index(request):
    if request.user.is_authenticated:
        status_text_form = forms.StatusTextForm()
        comment_text_form = forms.CommentTextForm()
        offset = 0
        limit = 5
        friends = Friend.objects.filter((~Q(user_one_id=request.user.id) | ~Q(user_two_id=request.user.id))
                                        & Q(friendship_status=1)).all()

        friends_id = [request.user.id]
        for friend in friends:
            if request.user.id == friend.user_one_id:
                friends_id.append(friend.user_two_id)
            elif request.user.id == friend.user_two_id:
                friends_id.append(friend.user_one_id)
            else:
                pass
        posts = available_status_result(offset, limit, friends_id)
        page_name = 'Home'
        other_users = friend_request_not_send_yet_users(request.user.id)  # list of user to whom friend request hasn't been sent yet
        # return HttpResponse(other_users)
        if request.method == 'POST':
            status_text_form = forms.StatusTextForm(request.POST)
            if status_text_form.is_valid():
                status_message = models.Post()
                status_message.post_text = status_text_form.data['status_text']
                status_message.post_status = True
                status_message.user_id = request.user.id
                status_message.save()

                # send friends notification about post add
                post_id = models.Post.objects.filter(user_id=request.user.id).latest('id')

                for friend_id in friends_id:
                    current_site = get_current_site(request)
                    comment_notification = Notification()
                    comment_notification.from_user_id = request.user.id
                    comment_notification.to_user_id = friend_id
                    comment_notification.notification_text = '<a href="' \
                                                             'https://' + current_site.domain + '/status_details/' + \
                                                             str(post_id.pk) + '">' \
                                                             + request.user.first_name + ' ' + request.user.last_name + ' added a post.</a>'
                    if friend_id == request.user.id:
                        pass
                    else:
                        comment_notification.save()

                return redirect('/')
        # post = models.Post.objects.get(id=1)
        # return HttpResponse(post.comments.all())
        if posts.count() > 0:
            last_item_id = posts[posts.count() - 1].id
        else:
            last_item_id = 0
            
        return render(request, 'home/home.html', {'page_name': page_name, 'status_text_form': status_text_form,
                                                  'posts': posts, 'comment_text_form': comment_text_form,
                                                  'last_item_id': last_item_id, 'other_users': other_users
                                                  })
    else:
        return redirect('login/')


def available_status_result(offset, limit, friends_id):
    # get 5 status texts every time which are active and order by created_at
    # also excluded those status texts which are already shown in template page, and get other 5 status texts
    return models.Post.objects.filter(post_status=True, user_id__in=friends_id).order_by('-created_at')
    # return models.Post.objects.filter(post_status=True).order_by('-created_at')[offset: limit]


def friend_request_not_send_yet_users(user_id):
    user_in_friend_table = Friend.objects.filter(Q(user_one_id=user_id) | Q(user_two_id=user_id)).values('user_one_id', 'user_two_id')
    user_id_list = []
    for u in user_in_friend_table:
        if u['user_one_id'] not in user_id_list:
            user_id_list.append(u['user_one_id'])

        if u['user_two_id'] not in user_id_list:
            user_id_list.append(u['user_two_id'])
    user_id_list.append(user_id)
    return User.objects.exclude(id__in=user_id_list).filter(~Q(is_superuser=True) & Q(is_active=True))


@login_required(login_url='/')
def comment_add(request):
    '''
    Add a comment to a post
    :param request:
    :return:
    '''
    if request.user.is_authenticated:
        if request.method == 'POST':
            comment_add_form = forms.CommentTextForm(request.POST)
            if comment_add_form.is_valid():
                comment_text_add = models.Comment()
                comment_text_add.comment_text = comment_add_form.data['comment_text']
                comment_text_add.post_id = request.POST['post_id']
                comment_text_add.user_id = request.user.id
                comment_text_add.save()

                comments = models.Comment.objects.filter(post_id=comment_text_add.post_id)

                post_info = models.Post.objects.get(id=request.POST['post_id'])
                if post_info.user_id == request.user.id:
                    pass
                else:
                    current_site = get_current_site(request)
                    comment_notification = Notification()
                    comment_notification.from_user_id = request.user.id
                    comment_notification.to_user_id = post_info.user_id
                    comment_notification.notification_text = '<a href="' \
                                                             'https://'+current_site.domain+'/status_details/' +\
                                                             request.POST['post_id']+'">'\
                                                             + request.user.username+' commented on your status.</a>'
                    comment_notification.save()
                return render(request, 'home/comments.html', {'comments': comments})
    else:
        return redirect('login/')


def more_status_after_mouse_scroll(request, last_item_id):
    if request.user.is_authenticated:
        offset = 5
        limit = 5

        posts = available_status_result(offset, limit)
        print(posts.query)
        comment_text_form = forms.CommentTextForm()
        if len(posts) > 0:
            last_item_id = posts[len(posts) - 1].id
        else:
            last_item_id = 0
        return render(request, 'home/more_status_after_mouse_scroll.html', {'posts': posts,
                                                                            'comment_text_form': comment_text_form,
                                                                            'last_item_id': last_item_id})
    else:
        return redirect('login/')


@login_required(login_url='/')
def status_details(request, post_id):
    try:
        post_info = models.Post.objects.get(id=post_id)

        # check if the user who post the status and the user who are trying to read the post are friends
        friendship_info = Friend.objects.filter((Q(user_one_id=request.user.id) & Q(user_two_id=post_info.user_id)) |
                                                (Q(user_one_id=post_info.user_id) & Q(user_two_id=request.user.id))
                                                & Q(friendship_status=1))
        if request.user.id == post_info.user_id or len(friendship_info) > 0:
            comment_text_form = forms.CommentTextForm()
            page_name = 'Status details'
            return render(request, 'home/status_details.html', {'post': post_info, 'page_name': page_name,
                                                                'comment_text_form': comment_text_form})
        else:
            messages.error(request, 'You do not have rights to read other user post. First create a friendship')
            return HttpResponseRedirect('/')
    except models.Post.DoesNotExist:
        messages.error(request, 'No post found.')
        return HttpResponseRedirect('/')


@login_required(login_url='/')
def edit_post(request, post_id):
    '''
    edit a post
    :param request:
    :param post_id:
    :return:
    '''
    check_status_by_valid_user = models.Post.objects.get(user_id=request.user.id, id=post_id)

    try:
        status_text_form = forms.StatusTextForm(initial={'status_text': check_status_by_valid_user.post_text})
        if request.method == 'POST':
            status_text_form = forms.StatusTextForm(request.POST)
            if status_text_form.is_valid():
                status_message = models.Post.objects.get(user_id=request.user.id, id=post_id)
                status_message.post_text = status_text_form.data['status_text']
                status_message.save()
                return HttpResponseRedirect('/status_details/'+post_id)
        return render(request, 'home/edit_post.html', {'page_name': 'Edit post', 'status_text_form': status_text_form})
    except models.Post.DoesNotExist:
        return HttpResponseRedirect('/')


@login_required(login_url='/')
def delete_post(request, post_id):
    '''
    Delete a post and also it's associate comments
    :param request:
    :param post_id:
    :return:
    '''
    check_status_by_valid_user = models.Post.objects.get(user_id=request.user.id, id=post_id)

    try:
        associated_comments = models.Comment.objects.filter(user_id=request.user.id, id=post_id)

        if len(associated_comments) > 0:
            for associated_comment in associated_comments:
                associated_comment.delete()

        check_status_by_valid_user.delete()

home/templates/home/comments.html
{% load static from staticfiles %}
<ul class="comments_list">
    {% for each in comments %}
    <li id="comment_li_{{ each.id }}">
        <div class="image_of_comment_user">
            {% if each.user.normaluser.profile_photo == '' %}
                <img src="{% static "normaluser/images/avatar_2x.png" %}" alt="avatar">
            {% else %}
                <img src="{% static each.user.normaluser.profile_photo.url %}" alt="avatar">
            {% endif %}
            <span class="username_text">
                {% if each.user.id == user.id %}
                    {{ each.user.first_name }} {{ each.user.last_name }}
                {% else %}
                    <a href="{% url 'normaluser:other' each.user  %}">
                        {{ each.user.first_name }} {{ each.user.last_name }}
                    </a>
                {% endif %}
            </span>
            {% now "Y-m-d" as todays_date %}
            {% if each.created_at|date:"Y-m-d" == todays_date %}
                <span class="date_time_text">{{ each.created_at|timesince }} ago</span>
            {% else %}
                <span class="date_time_text">on {{ post.created_at|date:"D d M Y" }}</span>
            {% endif %}
        </div>
        <div class="comment_text">
            <p id="comment_area_{{ each.id }}" style="float: left;">
                {{ each.comment_text }}
            </p>
            {% if user.id == post.user_id or request.user.id == each.user_id %}
            <span style="float: right;">
                <a href="javascript:void(0)" data-toggle="popover" data-placement="bottom" data-toggle="popover" data-post_id="{{ each.id }}">
                    <i class="fa fa-ellipsis-h"></i>
                </a>
            </span>
            {% endif %}
            <div id="popover-content-{{ each.id }}" style="display: none">
                <ul class="list-group custom-popover">
                    {% if request.user.id == each.user_id %}
                        <li class="list-group-item"><a class="edit_comment_event" data-comment_id="{{ each.id }}">Edit</a></li>
                    {% endif %}
                    <li class="list-group-item">
                        <a
                                class="delete_comment"
                                data-post_id="{{ each.post.id }}"
                                data-comment_id="{{ each.id }}">Delete
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

home/templates/home/status_details.html
{% extends "layout.html" %}
{% block title %} Home {% endblock %}
{% load static from staticfiles %}
{% block static %}
    <link rel="stylesheet" type="text/css" href="{% static 'friends/css/friends.css' %}">
    <script src="{% static '/home/js/home.js' %}"></script>
{% endblock %}
{% block content %}
<div id="status-view-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12 friends" style="margin-top: 20px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <section class="post-heading">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="media">
                                        <div class="media-left">
                                            <a href="#">
                                                {% if post.user.normaluser.profile_photo == '' %}
                                                    <img src="{% static "normaluser/images/avatar_2x.png" %}" width="40" height="40" alt="avatar">
                                                {% else %}
                                                    <img src="{% static post.user.normaluser.profile_photo.url %}" width="40" height="40" alt="avatar">
                                                {% endif %}
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <a href="javascript:void(0)" class="anchor-username">
                                                <h4 class="media-heading">{{ post.user.first_name }} {{ post.user.last_name }}</h4>
                                            </a>
                                            {% now "Y-m-d" as todays_date %}
                                            {% if post.created_at|date:"Y-m-d" == todays_date %}
                                                <a href="javascript:void(0)" class="anchor-time">{{ post.created_at|timesince }} ago</a>
                                            {% else %}
                                                <a href="javascript:void(0)" class="anchor-time">{{ post.created_at|date:"Y-m-d H:i" }}</a>
                                            {% endif %}
                                        </div>
                                        {% if user.id == post.user_id %}
                                            <div class="media-right">
                                                <a href="javascript:void(0)" data-toggle="popover" data-placement="bottom" data-toggle="popover" data-post_id="{{ post.id }}">
                                                    <i class="fa fa-ellipsis-h"></i>
                                                </a>
                                            </div>

                                            <div id="popover-content-{{ post.id }}" style="display: none">
                                                <ul class="list-group custom-popover">
                                                    <li class="list-group-item"><a href="{% url 'home:edit_post' post.id %}" onclick="return confirm('Are you sure?')">Edit</a></li>
                                                    <li class="list-group-item"><a href="{% url 'home:delete_post' post.id %}" onclick="return confirm('Are you sure?')">Delete</a></li>
                                                </ul>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </section>
                        <section class="post-body">
                            <p>{{ post.post_text }}</p>
                        </section>
                        <section class="post-footer">

                            <div class="post-footer-comment-wrapper">
                                <div class="comment-form">
                                    <form role="form" class="form-horizontal comment_submit" method="post" id="comment_add_{{ post.id }}">
                                        {% csrf_token %}
                                        <input type="hidden" name="post_id" value="{{ post.id }}" />
                                        {% for field in comment_text_form.visible_fields %}
                                            {% if field.errors %}
                                                <div class="input-group error">
                                                    {{ field }}
                                                    <span class="input-group-btn">
                                                        <button class="btn btn-info" type="submit">Comment</button>
                                                    </span>
                                                    <span class="help-inline">
                                                        {% for error in  field.errors %}{{ error }}{% endfor %}
                                                    </span>
                                                </div>
                                            {% else %}
                                                <div class="input-group">
                                                    {{ field }}
                                                    <span class="input-group-btn">
                                                        <button class="btn btn-info" type="submit">Comment</button>
                                                    </span>
                                                    {% if field.help_text %}
                                                        <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                                    {% endif %}
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                        {% for field in comment_text_form.hidden_fields %}
                                            <div class="input-group">
                                                {{ field }}
                                            </div>
                                        {% endfor %}
                                        {% for field in comment_text_form.non_field_errors %}
                                            <div class="form-group has-error has-feedback">
                                                <div class="controls">
                                                    <span class="help-block">
                                                        {{ field }}
                                                    </span>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </form>
                                </div>
                                <hr>
                                <div class="comment_of_status" id="comment_of_status_{{ post.id }}">
                                    <ul class="comments_list">
                                        {% for each in post.comments.all|dictsort:'updated_at' %}
                                        <li id="comment_li_{{ each.id }}">
                                            <div class="image_of_comment_user">
                                                {% if each.user.normaluser.profile_photo == '' %}
                                                    <img src="{% static "normaluser/images/avatar_2x.png" %}" alt="avatar">
                                                {% else %}
                                                    <img src="{% static each.user.normaluser.profile_photo.url %}" alt="avatar">
                                                {% endif %}
                                                <span class="username_text">
                                                    <a href="{% url 'normaluser:other' each.user  %}">
                                                        {{ each.user }}
                                                    </a>
                                                </span>
                                                {% now "Y-m-d" as todays_date %}
                                                {% if each.created_at|date:"Y-m-d" == todays_date %}
                                                    <span class="date_time_text">{{ each.created_at|timesince }} ago</span>
                                                {% else %}
                                                    <span class="date_time_text">on {{ each.created_at|date:"D d M Y H:i:s" }}</span>
                                                {% endif %}
                                            </div>
                                            <div class="comment_text">
                                                <p id="comment_area_{{ each.id }}" style="float: left;">
                                                    {{ each.comment_text }}
                                                </p>
                                                {% if user.id == post.user_id or request.user.id == each.user_id %}
                                                <span style="float: right;">
                                                    <a href="javascript:void(0)" data-toggle="popover-comment" data-placement="bottom" data-toggle="popover" data-post_id="{{ each.id }}">
                                                        <i class="fa fa-ellipsis-h"></i>
                                                    </a>
                                                </span>
                                                {% endif %}
                                                <div id="popover-comment-content-{{ each.id }}" style="display: none">
                                                    <ul class="list-group custom-popover">
                                                        {% if request.user.id == each.user_id %}
                                                            <li class="list-group-item">
                                                                <a class="edit_comment_event" data-comment_id="{{ each.id }}">Edit</a>
                                                            </li>
                                                        {% endif %}
                                                        <li class="list-group-item">
                                                            <a
                                                                class="delete_comment"
                                                                data-post_id="{{ post.id }}"
                                                                data-comment_id="{{ each.id }}">Delete
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}