bwa2018djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from normaluser import views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('registration/', views.user_registration, name='registration'),
    path('registration/email_authenticate_registration/<slug:email_validation_code>',
         views.email_authenticate_registration, name='email_authenticate_registration'),
    path('password_reset/', views.user_password_reset, name='password_reset'),
    path('password_recover/<slug:username>', views.password_recover, name='password_recover'),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('normaluser.urls', 'normaluser'), namespace='normaluser')),
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
    path('discussion/', include(('discussion.urls', 'discussion'), namespace='discussion')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),  # for social login authentication
]

urlpatterns += staticfiles_urlpatterns()

discussion/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bwa2018djangoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='discussion'),
    path('create_new_discussion', views.create_new_discussion, name='create_new_discussion'),
    path('all_discussions', views.all_discussions, name='see_all_discussion'),
    path('get_discussion_head_texts/<slug:discussion_head_id>', views.get_discussion_head_texts,
         name='get_discussion_head_texts'),
    path('save_chat', views.save_chat, name='save_chat'),
    path('discussion_head_view_update', views.discussion_head_view_update, name='discussion_head_view_update'),
    path('add_chat_after_view/<slug:discussion_head_id>', views.add_chat_after_view, name='add_chat_after_view'),
    path('discussion_head_lists_update/<slug:discussion_head_id>', views.discussion_head_lists_update, name='discussion_head_lists_update'),
    path('message/<slug:discussion_head_id>', views.message, name='message'),
    path('all_discussion_search_result', views.all_discussion_search_result, name='all_discussion_search_result'),
    path('single_discussion_search_result', views.single_discussion_search_result, name='single_discussion_search_result'),
    path('get_discussion_info', views.get_discussion_info, name='get_discussion_info'),
    path('get_message/<slug:chat_id>', views.get_message, name='get_message'),
    path('chat_update', views.chat_update, name='chat_update'),
    path('cancel_message_edit/<slug:chat_id>/<slug:head_id>', views.cancel_message_edit, name='cancel_message_edit'),
    path('delete_chat/<slug:chat_id>', views.delete_chat, name="delete_chat"),
    path('delete_discussion_head/<slug:discussion_head_id>', views.delete_discussion_head, name='delete_discussion_head')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bwa2018djangoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('comment_add/', views.comment_add, name='comment_add'),
    path('more_status_after_mouse_scroll/<slug:last_item_id>', views.more_status_after_mouse_scroll,
         name='more_status_after_mouse_scroll'),
    path('status_details/<slug:post_id>', views.status_details,
         name='status'),
    path('edit_post/<slug:post_id>', views.edit_post, name='edit_post'),
    path('delete_post/<slug:post_id>', views.delete_post, name='delete_post'),
    path('get_comment/<slug:comment_id>', views.get_comment, name='get_comment'),
    path('delete_comment/<slug:comment_id>/<slug:post_id>', views.delete_comment, name='delete_comment'),
    path('cancel_comment_edit/<slug:comment_id>/<slug:post_id>', views.cancel_comment_edit, name='cancel_comment_edit'),
    path('comment_update', views.comment_update, name="comment_update")
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

discussion/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Discussion, DiscussionHead, DiscussionRecipient, DiscussionUserGroup


def must_be_empty(value):
    if value:
        raise forms.ValidationError('is not empty')


class DiscussionHeadForm(forms.Form):
    head_name = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Add new discussion head',
            'max-length': '255',
        }
    ))

    def clean(self):
        data = self.cleaned_data
        if data.get('head_name') == '':
            raise forms.ValidationError('Please write something before post.')

        if DiscussionHead.objects.filter(head_name=data.get('head_name')).exists():
            raise forms.ValidationError(
                "This head name already used. Try with new one."
            )
        data['head_name'] = data.get('head_name')

        return data

    class Meta:
        model = DiscussionHead
        fields = ['head_name']


class DiscussionForm(forms.Form):
    message = forms.CharField(required=True, widget=forms.TextInput(
        attrs={
            'class': 'write_msg',
            'max-length': '255',
            'placeholder': 'Type a message'
        }
    ))

    discussion_head_id = forms.CharField(required=True, widget=forms.HiddenInput)

    honeypot = forms.CharField(required=False, widget=forms.HiddenInput, label="Leave empty",
                               validators=[must_be_empty])

    def clean(self):
        data = self.cleaned_data
        data['message'] = data.get('message')
        data['discussion_head_id'] = data.get('discussion_head_id')
        return data

    class Meta:
        model = Discussion
        fields = ['message', 'discussion_head_id']

discussion/views.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from . import models
from . import forms
from django.db.models import Q
from notification.models import Notification
from friends.models import Friend
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
# Create your views here.


def index():
    pass


def create_new_discussion(request):
    '''
    all discussion head list view
    :param request:
    :return:
    '''
    friends_list = [request.user.id]
    new_discussion_form = forms.DiscussionHeadForm(request.POST)
    if new_discussion_form.is_valid():
        discussion_head = models.DiscussionHead()
        discussion_head.created_by_id = request.user.id
        discussion_head.head_name = request.POST['head_name']
        discussion_head.save()

        head_id = models.DiscussionHead.objects.filter(created_by_id=request.user.id).latest('id')
        last_head_id = head_id.pk

        user_friends = Friend.objects.filter((Q(user_one_id=request.user.id) | Q(user_two_id=request.user.id)) &
                                             Q(friendship_status=1)).all()

        if len(user_friends) > 0:
            comment_notification = Notification()
            comment_notification.from_user_id = request.user.id

            for user_friend in user_friends:
                if user_friend.user_one_id == request.user.id:
                    comment_notification.to_user_id = user_friend.user_two_id
                    friends_list.append(user_friend.user_two_id)
                else:
                    comment_notification.to_user_id = user_friend.user_one_id
                    friends_list.append(user_friend.user_one_id)
            sender_name = request.user.first_name+' '+request.user.last_name
            current_site = get_current_site(request)
            comment_notification.notification_text = '<a href="https://'+current_site.domain+'/discussion/message/' + \
                                                     str(last_head_id) + '">'+sender_name+' created a discussion group.</a>'
            comment_notification.save()

    heads = models.DiscussionHead.objects.filter(created_by_id__in=friends_list).distinct('id').order_by('id', 'messages__created_at')

    return render(request, 'discussion/discussion_form.html', {'discussion_head_form': new_discussion_form,
                                                               'discussion_heads': heads})


@login_required(login_url='login')
def all_discussions(request):
    '''
    Show all discussion head in templates
    :param request:
    :return:
    '''
    page_name = 'All discussion'
    try:
        discussion_head = models.DiscussionHead.objects.order_by('messages__created_at').values('id')
        if len(discussion_head) > 0:
            discussion_head = discussion_head[0]['id']
    except models.DiscussionHead.DoesNotExist:
        discussion_head = 0
    # return HttpResponse(discussion_head)
    discussion_form = forms.DiscussionForm(initial={'discussion_head_id': discussion_head})
    return render(request, 'discussion/all_discussion.html', {'page_name': page_name, 'discussion_form': discussion_form})


@login_required(login_url='login')
def get_discussion_head_texts(request, discussion_head_id):
    '''
    Show a specific discussion heads' messages
    :param request:
    :param discussion_head_id:
    :return:
    '''
    discussion_form = forms.DiscussionForm(initial={'discussion_head_id': discussion_head_id})
    chats = models.Discussion.objects.filter(discussion_head_id=discussion_head_id)
    return render(request, 'discussion/discussion_head_chats.html', {'chats': chats, 'discussion_form': discussion_form,
                                                                     'discussion_head_id': discussion_head_id})


@login_required(login_url='login')
def save_chat(request):
    '''
    Save a text message and send notification to those user who already have sent message in this specific discussion head
    :param request:
    :return:
    '''
    message_form = forms.DiscussionForm(request.POST)
    if message_form.is_valid():
        message_data = models.Discussion()
        message_data.message = message_form.cleaned_data['message']
        message_data.sender_id = request.user.id
        message_data.discussion_head_id = message_form.cleaned_data['discussion_head_id']
        message_data.save()

        message_id = models.Discussion.objects.filter(sender_id=request.user.id).latest('id')
        last_message_id = message_id.pk
        # check if current user is in the discussion head group
        if len(models.DiscussionUserGroup.objects.filter(Q(discussion_user_id=request.user.id) & Q(discussion_head_id=message_form.cleaned_data['discussion_head_id'])).all()) > 0:
            pass
        else:
            # add current user to the discussion user group
            user_group = models.DiscussionUserGroup()
            user_group.discussion_head_id = message_form.cleaned_data['discussion_head_id']
            user_group.discussion_user_id = request.user.id
            user_group.save()

        # get the list of discussion user groups
        discussion_users = models.DiscussionUserGroup.objects.filter(discussion_head_id=message_form.cleaned_data['discussion_head_id'])

        temp = []
        if len(discussion_users) > 0:  # check if discussion head has user groups
            for discussion_user in discussion_users:
                if discussion_user.discussion_user_id == request.user.id:
                    is_read = True
                else:
                    is_read = False

                temp = [
                    models.DiscussionRecipient(
                        is_read=is_read,
                        recipient_id=discussion_user.discussion_user_id,
                        discussion_head_id=message_form.cleaned_data['discussion_head_id'],
                        discussion_id=last_message_id
                    )
                ]
                models.DiscussionRecipient.objects.bulk_create(temp)
        # return HttpResponse(temp)
        else:
            discussion_recipient_object = models.DiscussionRecipient()
            discussion_recipient_object.is_read = True
            discussion_recipient_object.recipient_id = request.user.id
            discussion_recipient_object.discussion_id = message_id.pk
            discussion_recipient_object.save()
        return HttpResponse(1)

    return HttpResponse(0)


@login_required(login_url='login')
def discussion_head_view_update(request):
    '''
    Update discussion head to show if a new text message added to it every after 5 seconds
    :param request:
    :return:
    '''
    chats = ''
    discussion_head_id = 0
    try:
        user_friends = Friend.objects.filter((~Q(user_one_id=request.user.id) | ~Q(user_two_id=request.user.id)) &
                                             Q(friendship_status=1)).all()
        friends_list = [request.user.id]
        for user_friend in user_friends:
            if user_friend.user_one_id == request.user.id:
                friends_list.append(user_friend.user_two_id)
            else:
                friends_list.append(user_friend.user_one_id)

        discussion_head = models.DiscussionHead.objects.filter(created_by_id__in=friends_list).distinct('id').order_by(
            'id', 'messages__created_at').values('id')
        if len(discussion_head) > 0:
            discussion_head_id = discussion_head[0]['id']
            chats = models.Discussion.objects.filter(discussion_head_id=discussion_head_id)
    except models.DiscussionHead.DoesNotExist:
        discussion_head_id = 0
    discussion_form = forms.DiscussionForm(initial={'discussion_head_id': discussion_head_id})
    return render(request, 'discussion/all_discussion_update_view.html', {'discussion_form': discussion_form,
                                                                          'discussion_head_id': discussion_head_id,
                                                                          'chats': chats,
                                                                          })


@login_required(login_url='login')
def add_chat_after_view(request, discussion_head_id):
    '''
    Show text messages of a discussion head in template every after 5 seconds
    :param request:
    :param discussion_head_id:
    :return:
    '''

    try:
        chat_recipients = models.DiscussionRecipient.objects.filter(Q(discussion_head_id=discussion_head_id) & Q(recipient_id=request.user.id))
        if len(chat_recipients) > 0:
            for chat in chat_recipients:
                chat_update = models.DiscussionRecipient()
                chat_update.id = chat.id
                chat_update.discussion_id = chat.discussion_id
                chat_update.is_read = True
                chat_update.discussion_head_id = discussion_head_id
                chat_update.recipient_id = request.user.id
                chat_update.save()
    except models.DiscussionRecipient.DoesNotExist:
        pass
    chats = models.Discussion.objects.filter(discussion_head_id=discussion_head_id)
    return render(request, 'discussion/add_chat_after_view.html', {'discussion_head_id': discussion_head_id,
                                                                   'chats': chats})


@login_required(login_url='login')
def discussion_head_lists_update(request, discussion_head_id):
    '''
    Update discussion head lists of the menu bar to show user notification of new text messages after every 15 seconds
    :param request:
    :param discussion_head_id:
    :return:
    '''
    try:
        chats = models.DiscussionRecipient.objects.filter(Q(discussion_head_id=discussion_head_id) & Q(recipient_id=request.user.id))
        if len(chats) > 0:

templates/discussion/discussion.html
{% load static from staticfiles %}
{% now "Y-m-d" as todays_date %}
<li class="menu-li" id="discussion_li">
    <a class="dropdown-toggle discussion_icon" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#discussion">
        <i class="fa fa-comment"></i>
        <span class="badge badge-notify">
            {{ unread_discussion }}
        </span>
    </a>
    <ul class="dropdown-menu discussion_dropdown notify-drop">
        <div class="notify-drop-title">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                    <form class="form-inline" method="post" id="discussion_head_form">
                        {% csrf_token %}
                        {% for field in discussion_head_form %}
                            <div class="form-group">
                                <div class="controls">{{ field }}
                                    {% if field.help_text %}
                                        <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
        {% if discussion_heads %}
            <div class="drop-content">
                {% for discussion_head in discussion_heads %}
                <li {% if discussion_head.unread_count > 0 %}style="background-color: antiquewhite;" {% endif %}>
                    <a href="{% url 'discussion:message' discussion_head.id %}">
                        <div class="col-md-2 col-sm-2 col-xs-2">
                            <div class="notify-img">
                                {% if discussion_head.messages.all|length > 0 %}
                                    {% if discussion_head.messages.last.sender.normaluser.profile_photo == '' %}
                                        <img width="40" height="40" src="{% static "normaluser/images/avatar_2x.png" %}" alt="avatar">
                                    {% else %}
                                        <img width="40" height="40" src="{% static discussion_head.messages.last.sender.normaluser.profile_photo.url %}" alt="avatar">
                                    {% endif %}
                                {% else %}
                                    {% if discussion_head.created_by.normaluser.profile_photo == '' %}
                                        <img width="40" height="40" src="{% static "normaluser/images/avatar_2x.png" %}" alt="avatar">
                                    {% else %}
                                        <img width="40" height="40" src="{% static discussion_head.created_by.normaluser.profile_photo.url %}" alt="avatar">
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-md-10 col-sm-10 col-xs-10" >
                            <b>{{ discussion_head.head_name }}</b>
                            {% if discussion_head.messages.all|length > 0 %}
                                <p>{{ discussion_head.messages.last.message }}</p>
                                <span class="message_sent_by">{{ discussion_head.messages.last.sender.first_name }} {{ discussion_head.messages.last.sender.last_name }}</span>
                                {% if discussion_head.messages.last.updated_at|date:"Y-m-d" == todays_date %}
                                    <span class="message_sent_at">{{ discussion_head.messages.last.updated_at|timesince }} ago</span>
                                {% else %}
                                    <span class="message_sent_at">{{ discussion_head.messages.last.updated_at|date:"N j, o," }}
                                        {{ discussion_head.messages.last.updated_at|time:"P"}}
                                    </span>
                                {% endif %}
                            {% else %}
                                <p>Empty discussion in this head</p>
                                {% if discussion_head.updated_at|date:"Y-m-d" == todays_date %}
                                    <span class="message_sent_at">{{ discussion_head.updated_at|timesince }} ago</span>
                                {% else %}
                                    <span class="message_sent_at">{{ discussion_head.updated_at|date:"N j, o," }}
                                        {{ discussion_head.updated_at|time:"P"}}
                                    </span>
                                {% endif %}
                            {% endif %}
                        </div>
                    </a>
                </li>
                {% endfor %}
            </div>
            <div class="notify-drop-footer text-center">
                <a href="{% url 'discussion:see_all_discussion' %}">see all</a>
            </div>
        {% else %}
            <div class="notify-drop-footer text-center">
                No discussion found
            </div>
        {% endif %}
    </ul>
</li>