bwa2018djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from normaluser import views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('registration/', views.user_registration, name='registration'),
    path('registration/email_authenticate_registration/<slug:email_validation_code>',
         views.email_authenticate_registration, name='email_authenticate_registration'),
    path('password_reset/', views.user_password_reset, name='password_reset'),
    path('password_recover/<slug:username>', views.password_recover, name='password_recover'),
    path('friends/', include(('friends.urls', 'friends'), namespace='friends')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('profile/', include(('normaluser.urls', 'normaluser'), namespace='normaluser')),
    path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
    path('discussion/', include(('discussion.urls', 'discussion'), namespace='discussion')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),  # for social login authentication
]

urlpatterns += staticfiles_urlpatterns()

friends/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bwa2018djangoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.friend_list, name='friend_list'),
    path('create_friendship', views.create_friendship, name='create_friendship'),
    path('delete_friendship_request', views.delete_friendship_request, name='delete_friendship_request'),
    path('accept_friendship_request', views.accept_friendship_request, name='accept_friendship_request')
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bwa2018djangoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='home'),
    path('comment_add/', views.comment_add, name='comment_add'),
    path('more_status_after_mouse_scroll/<slug:last_item_id>', views.more_status_after_mouse_scroll,
         name='more_status_after_mouse_scroll'),
    path('status_details/<slug:post_id>', views.status_details,
         name='status'),
    path('edit_post/<slug:post_id>', views.edit_post, name='edit_post'),
    path('delete_post/<slug:post_id>', views.delete_post, name='delete_post'),
    path('get_comment/<slug:comment_id>', views.get_comment, name='get_comment'),
    path('delete_comment/<slug:comment_id>/<slug:post_id>', views.delete_comment, name='delete_comment'),
    path('cancel_comment_edit/<slug:comment_id>/<slug:post_id>', views.cancel_comment_edit, name='cancel_comment_edit'),
    path('comment_update', views.comment_update, name="comment_update")
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

normaluser/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from bwa2018djangoproject import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.profile, name='profile'),
    path(r'edit/', views.edit_profile, name='edit_profile'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('upload_profile_image', views.upload_profile_image, name='upload_profile_image'),
    path('delete_account', views.delete_account, name='delete_account'),
    # path('other/<slug:username1>.+', views.user_profile, name='other'),
    re_path(r'^other/(?P<username1>.*)/$', views.user_profile, name='other'),
    re_path(r'^user_search/$', views.user_search, name='user_search'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/frontend.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>
        {% block title %}
        {% endblock %}
        </title>
        <!--favicon section-->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'bwa2018djangoproject/frontend/images/favicon/apple-touch-icon.png' %}/">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'bwa2018djangoproject/frontend/images/favicon/favicon-32x32.png' %}/">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'bwa2018djangoproject/frontend/images/favicon/favicon-16x16.png' %}/">
        <link rel="mask-icon" href="{% static 'bwa2018djangoproject/frontend/images/favicon/safari-pinned-tab.svg' %}/" color="#5bbad5"/>
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <!--favicon section-->

        <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/bootstrap/css/bootstrap.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/bootstrap/css/bootstrap-theme.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/frontend/css/font-awesome.min.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/frontend/css/style.css' %}" >

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <script src="{% static 'bwa2018djangoproject/bootstrap/js/bootstrap.js' %}"></script>
        <script src="{% static 'bwa2018djangoproject/frontend/js/registration.js' %}"></script>

    {% block static %}{% endblock %}
    </head>
<body class="bg-gray">
    <div class="container">
    {% if messages %}
        <div class="row">
            <div class="col-sm-12 text-center">
            {% for message in messages %}
            <div data-alert class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
                {{ message }}
            </div>
            {% endfor %}
            </div>
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

templates/layout.html
{% load static %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
        <!--favicon section-->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'bwa2018djangoproject/frontend/images/favicon/apple-touch-icon.png' %}/">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'bwa2018djangoproject/frontend/images/favicon/favicon-32x32.png' %}/">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'bwa2018djangoproject/frontend/images/favicon/favicon-16x16.png' %}/">
        <link rel="mask-icon" href="{% static 'bwa2018djangoproject/frontend/images/favicon/safari-pinned-tab.svg' %}/" color="#5bbad5"/>
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <!--favicon section-->
    <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/bootstrap/css/bootstrap.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/bootstrap/css/bootstrap-theme.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/frontend/css/style.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/frontend/css/notification.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bwa2018djangoproject/frontend/css/font-awesome.min.css' %}" >
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="{% static 'bwa2018djangoproject/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'bwa2018djangoproject/frontend/js/notification.js' %}"></script>
    <script src="{% static 'bwa2018djangoproject/frontend/js/discussion.js' %}"></script>
    {% block static %}{% endblock %}
</head>
<body class="body">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header navbar-header-logo">
                <a href="{% url 'home:home' %}">
                    <img src="{% static 'bwa2018djangoproject/frontend/images/logo.png' %}" alt="app logo"/>
                </a>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <form class="navbar-form navbar-left form-inline col-sm-3" role="search">
                    <div class="input-group">
                          <input type="text" class="form-control" id="all_search" placeholder="Search here">
                            <span class="input-group-addon"><i class="fa fa-search" style="left: auto"></i></span>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right menu-ul">
                    <li class="{% if request.resolver_match.url_name == 'home' %}active{% endif %} menu-li">
                        <a class="menu-a" href="{% url 'home:home' %}">Home</a>
                    </li>
                    <li class="{% if request.resolver_match.url_name == 'profile' %}active{% endif %} menu-li">
                        <a class="menu-a" href="{% url 'normaluser:profile' %}">Profile</a>
                    </li>
                    <li class="{% if request.resolver_match.url_name == 'friend_list' %}active{% endif %} menu-li">
                        <a class="menu-a" href="{% url 'friends:friend_list' %}">Friends</a>
                    </li>

                    {% include "./discussion/discussion.html" %}
                    {% include "./notification/notification.html" %}

                    <li class="dropdown menu-li">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <div class="media-left">
                            {% if user.is_authenticated %}
                                {% if user.normaluser.profile_photo == '' %}
                                    <img src="{% static "normaluser/images/avatar_2x.png" %}" alt="user avatar" width="40" height="40" />
                                {% else %}
                                    <img src="{% static user.normaluser.profile_photo.url %}" alt="user avatar" width="40" height="40" />
                                {% endif %} {{user.last_name}}<span class="caret"></span>
                            {% endif %}
                        </div>

                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="menu-a" href="{% url 'normaluser:profile' %}">Profile</a></li>
                            <li><a class="menu-a" onClick="return confirm('You sure? All your data will be deleted.');" href="{% url 'normaluser:delete_account' %}">Delete account</a></li>
                            <li><a class="menu-a" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div id="page-title-info">
        <div class="container">
            {% if messages %}
            <div class="row">
                <div class="col-sm-12 text-center">
                {% for message in messages %}
                <div data-alert class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="row">
                <div class="col-md-6 page-name">
                    <h1>{{ page_name }}</h1>
                </div>
                <div class="col-md-6">

                </div>
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}
</body>
</html>